import "./Footer.scss";
import openailogo from "../../assets/icons/1290202.png"

function Footer() {
  return (
    <div className="footer">

    
      <h3>Disclaimer: Providing missinformation on your CV is not considered a legal practice. Please use this tool as guidance or inspiration. The data generated by the algorithm could be misleading and untruthy.</h3>
      <div className="openai"> 
      <h4>Powered by OpenAI</h4>
      <img className="openai__logo" alt="openai__logo" src={openailogo}/>

      
      </div>

      <h4> Copyright 2023</h4>
    </div>
  );
}

export default Footer
