import "./Footer.scss";
import openailogo from "../../assets/icons/1290202.png"

function Footer() {
  return (
    <div className="footer">

    
      <h3 className="footer__disclaimer">Disclaimer: Providing missleading information on your CV is not considered good practice. Please use this tool as guidance or inspiration for your CV formating. The data generated by the algorithm could be misleading.Always verify the fact integrity before sharing your "hacked" CV with third parties.</h3>
      <div className="openai"> 
      <h4>Powered by OpenAI</h4>
      <img className="openai__logo" alt="openai__logo" src={openailogo}/>

      
      </div>

      <h4> Copyright 2023 CVHACK. Non-commercial use only.</h4>
    </div>
  );
}

export default Footer
